# Generated by Django 3.1.7 on 2021-03-20 18:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=64)),
                ('country', models.CharField(choices=[('Russia', 'Russia'), ('USA', 'USA'), ('Germany', 'Germany'), ('France', 'France'), ('Japan', 'Japan')], default='Russia', max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='обновлен')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('in_stock', models.BooleanField(default=True)),
                ('diller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.organization')),
            ],
        ),
    ]
